/*
 * This file is generated by jOOQ.
 */
package dbconn.tables;


import dbconn.F1gamedb;
import dbconn.Keys;
import dbconn.tables.records.InstantlapdataRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 *  Lap Data that should be saved instantaneously. 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Instantlapdata extends TableImpl<InstantlapdataRecord> {

    private static final long serialVersionUID = -1898847761;

    /**
     * The reference instance of <code>F1GameDB.InstantLapData</code>
     */
    public static final Instantlapdata INSTANTLAPDATA = new Instantlapdata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstantlapdataRecord> getRecordType() {
        return InstantlapdataRecord.class;
    }

    /**
     * The column <code>F1GameDB.InstantLapData.idInstantData</code>.
     */
    public final TableField<InstantlapdataRecord, Integer> IDINSTANTDATA = createField(DSL.name("idInstantData"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>F1GameDB.InstantLapData.sessionId</code>.
     */
    public final TableField<InstantlapdataRecord, Long> SESSIONID = createField(DSL.name("sessionId"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>F1GameDB.InstantLapData.sessionTime</code>.
     */
    public final TableField<InstantlapdataRecord, Double> SESSIONTIME = createField(DSL.name("sessionTime"), org.jooq.impl.SQLDataType.FLOAT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>F1GameDB.InstantLapData.currentLapTime</code>.
     */
    public final TableField<InstantlapdataRecord, Double> CURRENTLAPTIME = createField(DSL.name("currentLapTime"), org.jooq.impl.SQLDataType.FLOAT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>F1GameDB.InstantLapData.totalDistance</code>.
     */
    public final TableField<InstantlapdataRecord, Double> TOTALDISTANCE = createField(DSL.name("totalDistance"), org.jooq.impl.SQLDataType.FLOAT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>F1GameDB.InstantLapData.lapDistance</code>.
     */
    public final TableField<InstantlapdataRecord, Double> LAPDISTANCE = createField(DSL.name("lapDistance"), org.jooq.impl.SQLDataType.FLOAT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * Create a <code>F1GameDB.InstantLapData</code> table reference
     */
    public Instantlapdata() {
        this(DSL.name("InstantLapData"), null);
    }

    /**
     * Create an aliased <code>F1GameDB.InstantLapData</code> table reference
     */
    public Instantlapdata(String alias) {
        this(DSL.name(alias), INSTANTLAPDATA);
    }

    /**
     * Create an aliased <code>F1GameDB.InstantLapData</code> table reference
     */
    public Instantlapdata(Name alias) {
        this(alias, INSTANTLAPDATA);
    }

    private Instantlapdata(Name alias, Table<InstantlapdataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Instantlapdata(Name alias, Table<InstantlapdataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(" Lap Data that should be saved instantaneously. "), TableOptions.table());
    }

    public <O extends Record> Instantlapdata(Table<O> child, ForeignKey<O, InstantlapdataRecord> key) {
        super(child, key, INSTANTLAPDATA);
    }

    @Override
    public Schema getSchema() {
        return F1gamedb.F1GAMEDB;
    }

    @Override
    public Identity<InstantlapdataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INSTANTLAPDATA;
    }

    @Override
    public UniqueKey<InstantlapdataRecord> getPrimaryKey() {
        return Keys.KEY_INSTANTLAPDATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<InstantlapdataRecord>> getKeys() {
        return Arrays.<UniqueKey<InstantlapdataRecord>>asList(Keys.KEY_INSTANTLAPDATA_PRIMARY);
    }

    @Override
    public Instantlapdata as(String alias) {
        return new Instantlapdata(DSL.name(alias), this);
    }

    @Override
    public Instantlapdata as(Name alias) {
        return new Instantlapdata(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Instantlapdata rename(String name) {
        return new Instantlapdata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Instantlapdata rename(Name name) {
        return new Instantlapdata(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, Double, Double, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
