/*
 * This file is generated by jOOQ.
 */
package dbconn.tables;


import dbconn.F1gamedb;
import dbconn.Keys;
import dbconn.tables.records.NationalitiesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Information of natinalities specified by F1 2018.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nationalities extends TableImpl<NationalitiesRecord> {

    private static final long serialVersionUID = -1328769420;

    /**
     * The reference instance of <code>F1GameDB.Nationalities</code>
     */
    public static final Nationalities NATIONALITIES = new Nationalities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NationalitiesRecord> getRecordType() {
        return NationalitiesRecord.class;
    }

    /**
     * The column <code>F1GameDB.Nationalities.idNationality</code>.
     */
    public final TableField<NationalitiesRecord, Short> IDNATIONALITY = createField(DSL.name("idNationality"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>F1GameDB.Nationalities.nationalityName</code>.
     */
    public final TableField<NationalitiesRecord, String> NATIONALITYNAME = createField(DSL.name("nationalityName"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>F1GameDB.Nationalities</code> table reference
     */
    public Nationalities() {
        this(DSL.name("Nationalities"), null);
    }

    /**
     * Create an aliased <code>F1GameDB.Nationalities</code> table reference
     */
    public Nationalities(String alias) {
        this(DSL.name(alias), NATIONALITIES);
    }

    /**
     * Create an aliased <code>F1GameDB.Nationalities</code> table reference
     */
    public Nationalities(Name alias) {
        this(alias, NATIONALITIES);
    }

    private Nationalities(Name alias, Table<NationalitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Nationalities(Name alias, Table<NationalitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Information of natinalities specified by F1 2018."), TableOptions.table());
    }

    public <O extends Record> Nationalities(Table<O> child, ForeignKey<O, NationalitiesRecord> key) {
        super(child, key, NATIONALITIES);
    }

    @Override
    public Schema getSchema() {
        return F1gamedb.F1GAMEDB;
    }

    @Override
    public UniqueKey<NationalitiesRecord> getPrimaryKey() {
        return Keys.KEY_NATIONALITIES_PRIMARY;
    }

    @Override
    public List<UniqueKey<NationalitiesRecord>> getKeys() {
        return Arrays.<UniqueKey<NationalitiesRecord>>asList(Keys.KEY_NATIONALITIES_PRIMARY);
    }

    @Override
    public Nationalities as(String alias) {
        return new Nationalities(DSL.name(alias), this);
    }

    @Override
    public Nationalities as(Name alias) {
        return new Nationalities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Nationalities rename(String name) {
        return new Nationalities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Nationalities rename(Name name) {
        return new Nationalities(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Short, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
