/*
 * This file is generated by jOOQ.
 */
package dbconn;


import dbconn.tables.Sessionbasics;
import dbconn.tables.Sessiondetails;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>F1GameDB</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SESSIONBASICS_BASIC2DRIVER_IDX = Indexes0.SESSIONBASICS_BASIC2DRIVER_IDX;
    public static final Index SESSIONBASICS_BASIC2NATIONALITY_IDX = Indexes0.SESSIONBASICS_BASIC2NATIONALITY_IDX;
    public static final Index SESSIONBASICS_BASIC2PLAYER_IDX = Indexes0.SESSIONBASICS_BASIC2PLAYER_IDX;
    public static final Index SESSIONBASICS_BASIC2TEAM_IDX = Indexes0.SESSIONBASICS_BASIC2TEAM_IDX;
    public static final Index SESSIONDETAILS_DETAIL2TRACK_IDX = Indexes0.SESSIONDETAILS_DETAIL2TRACK_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SESSIONBASICS_BASIC2DRIVER_IDX = Internal.createIndex("basic2Driver_idx", Sessionbasics.SESSIONBASICS, new OrderField[] { Sessionbasics.SESSIONBASICS.DRIVER }, false);
        public static Index SESSIONBASICS_BASIC2NATIONALITY_IDX = Internal.createIndex("basic2Nationality_idx", Sessionbasics.SESSIONBASICS, new OrderField[] { Sessionbasics.SESSIONBASICS.NATIONALITY }, false);
        public static Index SESSIONBASICS_BASIC2PLAYER_IDX = Internal.createIndex("basic2Player_idx", Sessionbasics.SESSIONBASICS, new OrderField[] { Sessionbasics.SESSIONBASICS.PLAYER }, false);
        public static Index SESSIONBASICS_BASIC2TEAM_IDX = Internal.createIndex("basic2Team_idx", Sessionbasics.SESSIONBASICS, new OrderField[] { Sessionbasics.SESSIONBASICS.TEAM }, false);
        public static Index SESSIONDETAILS_DETAIL2TRACK_IDX = Internal.createIndex("detail2Track_idx", Sessiondetails.SESSIONDETAILS, new OrderField[] { Sessiondetails.SESSIONDETAILS.TRACKID }, false);
    }
}
