/*
 * This file is generated by jOOQ.
 */
package dbconn;


import dbconn.tables.Drivers;
import dbconn.tables.Employees;
import dbconn.tables.Nationalities;
import dbconn.tables.Players;
import dbconn.tables.Sessionbasics;
import dbconn.tables.Sessiondetails;
import dbconn.tables.Sessionendstatus;
import dbconn.tables.Sessionperformance;
import dbconn.tables.Sessionstatistics;
import dbconn.tables.Teams;
import dbconn.tables.Tracks;


/**
 * Convenience access to all tables in F1GameDB
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Store names of all drivers specified by F1 2018.
     */
    public static final Drivers DRIVERS = Drivers.DRIVERS;

    /**
     * The table <code>F1GameDB.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * Information of natinalities specified by F1 2018.
     */
    public static final Nationalities NATIONALITIES = Nationalities.NATIONALITIES;

    /**
     * Store information of players, specified by user. 
     */
    public static final Players PLAYERS = Players.PLAYERS;

    /**
     * Basic information of the game session: link player to driver, team, car used in this session. 
     */
    public static final Sessionbasics SESSIONBASICS = Sessionbasics.SESSIONBASICS;

    /**
     * Detailed informations about the track settings. 
     */
    public static final Sessiondetails SESSIONDETAILS = Sessiondetails.SESSIONDETAILS;

    /**
     * Car status at the end of the session: damages fuel remainings etc. 
     */
    public static final Sessionendstatus SESSIONENDSTATUS = Sessionendstatus.SESSIONENDSTATUS;

    /**
     * Information related to the performance during a session: max speed, lap time, etc. 
     */
    public static final Sessionperformance SESSIONPERFORMANCE = Sessionperformance.SESSIONPERFORMANCE;

    /**
     * Statistic information about how the player controllers the game, such as what buttons are pressed, temperature, etc. 
     */
    public static final Sessionstatistics SESSIONSTATISTICS = Sessionstatistics.SESSIONSTATISTICS;

    /**
     * Store information of all teams specified by F1 2018.
     */
    public static final Teams TEAMS = Teams.TEAMS;

    /**
     * Tracks information specified by F1 2018.
     */
    public static final Tracks TRACKS = Tracks.TRACKS;
}
