/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Carstatusdata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Necessary informaiton from CarStatus packet. Not needed to update quickly, 
 * 1Hz should be good enough. 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarstatusdataRecord extends UpdatableRecordImpl<CarstatusdataRecord> implements Record14<Integer, Long, Double, Double, Short, Short, Short, Short, Short, Short, Short, Short, Short, Short> {

    private static final long serialVersionUID = -1274360497;

    /**
     * Setter for <code>F1GameDB.CarStatusData.idCarStatusData</code>.
     */
    public void setIdcarstatusdata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.idCarStatusData</code>.
     */
    public Integer getIdcarstatusdata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.sessionId</code>.
     */
    public void setSessionid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.sessionId</code>.
     */
    public Long getSessionid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.sessionTime</code>.
     */
    public void setSessiontime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.sessionTime</code>.
     */
    public Double getSessiontime() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.fuelInTank</code>.
     */
    public void setFuelintank(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.fuelInTank</code>.
     */
    public Double getFuelintank() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.frontLeftWingDamage</code>.
     */
    public void setFrontleftwingdamage(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.frontLeftWingDamage</code>.
     */
    public Short getFrontleftwingdamage() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.frontRightWingDamage</code>.
     */
    public void setFrontrightwingdamage(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.frontRightWingDamage</code>.
     */
    public Short getFrontrightwingdamage() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.rearWingDamage</code>.
     */
    public void setRearwingdamage(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.rearWingDamage</code>.
     */
    public Short getRearwingdamage() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.engineDamage</code>.
     */
    public void setEnginedamage(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.engineDamage</code>.
     */
    public Short getEnginedamage() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.gearBoxDamage</code>.
     */
    public void setGearboxdamage(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.gearBoxDamage</code>.
     */
    public Short getGearboxdamage() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.exhaustDamage</code>.
     */
    public void setExhaustdamage(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.exhaustDamage</code>.
     */
    public Short getExhaustdamage() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.tyreRLDamage</code>.
     */
    public void setTyrerldamage(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.tyreRLDamage</code>.
     */
    public Short getTyrerldamage() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.tyreRRDamage</code>.
     */
    public void setTyrerrdamage(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.tyreRRDamage</code>.
     */
    public Short getTyrerrdamage() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.tyreFLDamage</code>.
     */
    public void setTyrefldamage(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.tyreFLDamage</code>.
     */
    public Short getTyrefldamage() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>F1GameDB.CarStatusData.tyreFRDamage</code>.
     */
    public void setTyrefrdamage(Short value) {
        set(13, value);
    }

    /**
     * Getter for <code>F1GameDB.CarStatusData.tyreFRDamage</code>.
     */
    public Short getTyrefrdamage() {
        return (Short) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Long, Double, Double, Short, Short, Short, Short, Short, Short, Short, Short, Short, Short> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Long, Double, Double, Short, Short, Short, Short, Short, Short, Short, Short, Short, Short> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Carstatusdata.CARSTATUSDATA.IDCARSTATUSDATA;
    }

    @Override
    public Field<Long> field2() {
        return Carstatusdata.CARSTATUSDATA.SESSIONID;
    }

    @Override
    public Field<Double> field3() {
        return Carstatusdata.CARSTATUSDATA.SESSIONTIME;
    }

    @Override
    public Field<Double> field4() {
        return Carstatusdata.CARSTATUSDATA.FUELINTANK;
    }

    @Override
    public Field<Short> field5() {
        return Carstatusdata.CARSTATUSDATA.FRONTLEFTWINGDAMAGE;
    }

    @Override
    public Field<Short> field6() {
        return Carstatusdata.CARSTATUSDATA.FRONTRIGHTWINGDAMAGE;
    }

    @Override
    public Field<Short> field7() {
        return Carstatusdata.CARSTATUSDATA.REARWINGDAMAGE;
    }

    @Override
    public Field<Short> field8() {
        return Carstatusdata.CARSTATUSDATA.ENGINEDAMAGE;
    }

    @Override
    public Field<Short> field9() {
        return Carstatusdata.CARSTATUSDATA.GEARBOXDAMAGE;
    }

    @Override
    public Field<Short> field10() {
        return Carstatusdata.CARSTATUSDATA.EXHAUSTDAMAGE;
    }

    @Override
    public Field<Short> field11() {
        return Carstatusdata.CARSTATUSDATA.TYRERLDAMAGE;
    }

    @Override
    public Field<Short> field12() {
        return Carstatusdata.CARSTATUSDATA.TYRERRDAMAGE;
    }

    @Override
    public Field<Short> field13() {
        return Carstatusdata.CARSTATUSDATA.TYREFLDAMAGE;
    }

    @Override
    public Field<Short> field14() {
        return Carstatusdata.CARSTATUSDATA.TYREFRDAMAGE;
    }

    @Override
    public Integer component1() {
        return getIdcarstatusdata();
    }

    @Override
    public Long component2() {
        return getSessionid();
    }

    @Override
    public Double component3() {
        return getSessiontime();
    }

    @Override
    public Double component4() {
        return getFuelintank();
    }

    @Override
    public Short component5() {
        return getFrontleftwingdamage();
    }

    @Override
    public Short component6() {
        return getFrontrightwingdamage();
    }

    @Override
    public Short component7() {
        return getRearwingdamage();
    }

    @Override
    public Short component8() {
        return getEnginedamage();
    }

    @Override
    public Short component9() {
        return getGearboxdamage();
    }

    @Override
    public Short component10() {
        return getExhaustdamage();
    }

    @Override
    public Short component11() {
        return getTyrerldamage();
    }

    @Override
    public Short component12() {
        return getTyrerrdamage();
    }

    @Override
    public Short component13() {
        return getTyrefldamage();
    }

    @Override
    public Short component14() {
        return getTyrefrdamage();
    }

    @Override
    public Integer value1() {
        return getIdcarstatusdata();
    }

    @Override
    public Long value2() {
        return getSessionid();
    }

    @Override
    public Double value3() {
        return getSessiontime();
    }

    @Override
    public Double value4() {
        return getFuelintank();
    }

    @Override
    public Short value5() {
        return getFrontleftwingdamage();
    }

    @Override
    public Short value6() {
        return getFrontrightwingdamage();
    }

    @Override
    public Short value7() {
        return getRearwingdamage();
    }

    @Override
    public Short value8() {
        return getEnginedamage();
    }

    @Override
    public Short value9() {
        return getGearboxdamage();
    }

    @Override
    public Short value10() {
        return getExhaustdamage();
    }

    @Override
    public Short value11() {
        return getTyrerldamage();
    }

    @Override
    public Short value12() {
        return getTyrerrdamage();
    }

    @Override
    public Short value13() {
        return getTyrefldamage();
    }

    @Override
    public Short value14() {
        return getTyrefrdamage();
    }

    @Override
    public CarstatusdataRecord value1(Integer value) {
        setIdcarstatusdata(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value2(Long value) {
        setSessionid(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value3(Double value) {
        setSessiontime(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value4(Double value) {
        setFuelintank(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value5(Short value) {
        setFrontleftwingdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value6(Short value) {
        setFrontrightwingdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value7(Short value) {
        setRearwingdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value8(Short value) {
        setEnginedamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value9(Short value) {
        setGearboxdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value10(Short value) {
        setExhaustdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value11(Short value) {
        setTyrerldamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value12(Short value) {
        setTyrerrdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value13(Short value) {
        setTyrefldamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord value14(Short value) {
        setTyrefrdamage(value);
        return this;
    }

    @Override
    public CarstatusdataRecord values(Integer value1, Long value2, Double value3, Double value4, Short value5, Short value6, Short value7, Short value8, Short value9, Short value10, Short value11, Short value12, Short value13, Short value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarstatusdataRecord
     */
    public CarstatusdataRecord() {
        super(Carstatusdata.CARSTATUSDATA);
    }

    /**
     * Create a detached, initialised CarstatusdataRecord
     */
    public CarstatusdataRecord(Integer idcarstatusdata, Long sessionid, Double sessiontime, Double fuelintank, Short frontleftwingdamage, Short frontrightwingdamage, Short rearwingdamage, Short enginedamage, Short gearboxdamage, Short exhaustdamage, Short tyrerldamage, Short tyrerrdamage, Short tyrefldamage, Short tyrefrdamage) {
        super(Carstatusdata.CARSTATUSDATA);

        set(0, idcarstatusdata);
        set(1, sessionid);
        set(2, sessiontime);
        set(3, fuelintank);
        set(4, frontleftwingdamage);
        set(5, frontrightwingdamage);
        set(6, rearwingdamage);
        set(7, enginedamage);
        set(8, gearboxdamage);
        set(9, exhaustdamage);
        set(10, tyrerldamage);
        set(11, tyrerrdamage);
        set(12, tyrefldamage);
        set(13, tyrefrdamage);
    }
}
