/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Instantlapdata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 *  Lap Data that should be saved instantaneously. 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstantlapdataRecord extends UpdatableRecordImpl<InstantlapdataRecord> implements Record6<Integer, Long, Double, Double, Double, Double> {

    private static final long serialVersionUID = 658224507;

    /**
     * Setter for <code>F1GameDB.InstantLapData.idInstantData</code>.
     */
    public void setIdinstantdata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.InstantLapData.idInstantData</code>.
     */
    public Integer getIdinstantdata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>F1GameDB.InstantLapData.sessionId</code>.
     */
    public void setSessionid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.InstantLapData.sessionId</code>.
     */
    public Long getSessionid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>F1GameDB.InstantLapData.sessionTime</code>.
     */
    public void setSessiontime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>F1GameDB.InstantLapData.sessionTime</code>.
     */
    public Double getSessiontime() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>F1GameDB.InstantLapData.currentLapTime</code>.
     */
    public void setCurrentlaptime(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>F1GameDB.InstantLapData.currentLapTime</code>.
     */
    public Double getCurrentlaptime() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>F1GameDB.InstantLapData.totalDistance</code>.
     */
    public void setTotaldistance(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>F1GameDB.InstantLapData.totalDistance</code>.
     */
    public Double getTotaldistance() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>F1GameDB.InstantLapData.lapDistance</code>.
     */
    public void setLapdistance(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>F1GameDB.InstantLapData.lapDistance</code>.
     */
    public Double getLapdistance() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, Double, Double, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Long, Double, Double, Double, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Instantlapdata.INSTANTLAPDATA.IDINSTANTDATA;
    }

    @Override
    public Field<Long> field2() {
        return Instantlapdata.INSTANTLAPDATA.SESSIONID;
    }

    @Override
    public Field<Double> field3() {
        return Instantlapdata.INSTANTLAPDATA.SESSIONTIME;
    }

    @Override
    public Field<Double> field4() {
        return Instantlapdata.INSTANTLAPDATA.CURRENTLAPTIME;
    }

    @Override
    public Field<Double> field5() {
        return Instantlapdata.INSTANTLAPDATA.TOTALDISTANCE;
    }

    @Override
    public Field<Double> field6() {
        return Instantlapdata.INSTANTLAPDATA.LAPDISTANCE;
    }

    @Override
    public Integer component1() {
        return getIdinstantdata();
    }

    @Override
    public Long component2() {
        return getSessionid();
    }

    @Override
    public Double component3() {
        return getSessiontime();
    }

    @Override
    public Double component4() {
        return getCurrentlaptime();
    }

    @Override
    public Double component5() {
        return getTotaldistance();
    }

    @Override
    public Double component6() {
        return getLapdistance();
    }

    @Override
    public Integer value1() {
        return getIdinstantdata();
    }

    @Override
    public Long value2() {
        return getSessionid();
    }

    @Override
    public Double value3() {
        return getSessiontime();
    }

    @Override
    public Double value4() {
        return getCurrentlaptime();
    }

    @Override
    public Double value5() {
        return getTotaldistance();
    }

    @Override
    public Double value6() {
        return getLapdistance();
    }

    @Override
    public InstantlapdataRecord value1(Integer value) {
        setIdinstantdata(value);
        return this;
    }

    @Override
    public InstantlapdataRecord value2(Long value) {
        setSessionid(value);
        return this;
    }

    @Override
    public InstantlapdataRecord value3(Double value) {
        setSessiontime(value);
        return this;
    }

    @Override
    public InstantlapdataRecord value4(Double value) {
        setCurrentlaptime(value);
        return this;
    }

    @Override
    public InstantlapdataRecord value5(Double value) {
        setTotaldistance(value);
        return this;
    }

    @Override
    public InstantlapdataRecord value6(Double value) {
        setLapdistance(value);
        return this;
    }

    @Override
    public InstantlapdataRecord values(Integer value1, Long value2, Double value3, Double value4, Double value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstantlapdataRecord
     */
    public InstantlapdataRecord() {
        super(Instantlapdata.INSTANTLAPDATA);
    }

    /**
     * Create a detached, initialised InstantlapdataRecord
     */
    public InstantlapdataRecord(Integer idinstantdata, Long sessionid, Double sessiontime, Double currentlaptime, Double totaldistance, Double lapdistance) {
        super(Instantlapdata.INSTANTLAPDATA);

        set(0, idinstantdata);
        set(1, sessionid);
        set(2, sessiontime);
        set(3, currentlaptime);
        set(4, totaldistance);
        set(5, lapdistance);
    }
}
