/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Motiondata;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This table includes necessary entries in Motion packet and some entries 
 * from other packet that requires instataneous update. The frequency should 
 * be as fast as possible. 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MotiondataRecord extends UpdatableRecordImpl<MotiondataRecord> {

    private static final long serialVersionUID = -1472637422;

    /**
     * Setter for <code>F1GameDB.MotionData.idMotionData</code>.
     */
    public void setIdmotiondata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.idMotionData</code>.
     */
    public Integer getIdmotiondata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.sessionId</code>.
     */
    public void setSessionid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.sessionId</code>.
     */
    public Long getSessionid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.sessionTime</code>.
     */
    public void setSessiontime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.sessionTime</code>.
     */
    public Double getSessiontime() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.worldVelocityX</code>.
     */
    public void setWorldvelocityx(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.worldVelocityX</code>.
     */
    public Double getWorldvelocityx() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.worldVelocityY</code>.
     */
    public void setWorldvelocityy(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.worldVelocityY</code>.
     */
    public Double getWorldvelocityy() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.worldVelocityZ</code>.
     */
    public void setWorldvelocityz(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.worldVelocityZ</code>.
     */
    public Double getWorldvelocityz() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.gForceLateral</code>.
     */
    public void setGforcelateral(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.gForceLateral</code>.
     */
    public Double getGforcelateral() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.gForceLongitudinal</code>.
     */
    public void setGforcelongitudinal(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.gForceLongitudinal</code>.
     */
    public Double getGforcelongitudinal() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.gForceVertical</code>.
     */
    public void setGforcevertical(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.gForceVertical</code>.
     */
    public Double getGforcevertical() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.yaw</code>.
     */
    public void setYaw(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.yaw</code>.
     */
    public Double getYaw() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.pitch</code>.
     */
    public void setPitch(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.pitch</code>.
     */
    public Double getPitch() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.roll</code>.
     */
    public void setRoll(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.roll</code>.
     */
    public Double getRoll() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionPositionRR</code>.
     */
    public void setSuspensionpositionrr(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionPositionRR</code>.
     */
    public Double getSuspensionpositionrr() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionPositionRL</code>.
     */
    public void setSuspensionpositionrl(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionPositionRL</code>.
     */
    public Double getSuspensionpositionrl() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionPositionFL</code>.
     */
    public void setSuspensionpositionfl(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionPositionFL</code>.
     */
    public Double getSuspensionpositionfl() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionPositionFR</code>.
     */
    public void setSuspensionpositionfr(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionPositionFR</code>.
     */
    public Double getSuspensionpositionfr() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionAccelerationRR</code>.
     */
    public void setSuspensionaccelerationrr(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionAccelerationRR</code>.
     */
    public Double getSuspensionaccelerationrr() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionVelocityRR</code>.
     */
    public void setSuspensionvelocityrr(Double value) {
        set(17, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionVelocityRR</code>.
     */
    public Double getSuspensionvelocityrr() {
        return (Double) get(17);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionVelocityRL</code>.
     */
    public void setSuspensionvelocityrl(Double value) {
        set(18, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionVelocityRL</code>.
     */
    public Double getSuspensionvelocityrl() {
        return (Double) get(18);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionVelocityFL</code>.
     */
    public void setSuspensionvelocityfl(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionVelocityFL</code>.
     */
    public Double getSuspensionvelocityfl() {
        return (Double) get(19);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionVelocityFR</code>.
     */
    public void setSuspensionvelocityfr(Double value) {
        set(20, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionVelocityFR</code>.
     */
    public Double getSuspensionvelocityfr() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.frontWheelsAngle</code>.
     */
    public void setFrontwheelsangle(Double value) {
        set(21, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.frontWheelsAngle</code>.
     */
    public Double getFrontwheelsangle() {
        return (Double) get(21);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionAccelerationRL</code>.
     */
    public void setSuspensionaccelerationrl(Double value) {
        set(22, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionAccelerationRL</code>.
     */
    public Double getSuspensionaccelerationrl() {
        return (Double) get(22);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionAccelerationFL</code>.
     */
    public void setSuspensionaccelerationfl(Double value) {
        set(23, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionAccelerationFL</code>.
     */
    public Double getSuspensionaccelerationfl() {
        return (Double) get(23);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.suspensionAccelerationFR</code>.
     */
    public void setSuspensionaccelerationfr(Double value) {
        set(24, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.suspensionAccelerationFR</code>.
     */
    public Double getSuspensionaccelerationfr() {
        return (Double) get(24);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.wheelSlipRR</code>.
     */
    public void setWheelsliprr(Double value) {
        set(25, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.wheelSlipRR</code>.
     */
    public Double getWheelsliprr() {
        return (Double) get(25);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.wheelSlipRL</code>.
     */
    public void setWheelsliprl(Double value) {
        set(26, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.wheelSlipRL</code>.
     */
    public Double getWheelsliprl() {
        return (Double) get(26);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.wheelSlipFL</code>.
     */
    public void setWheelslipfl(Double value) {
        set(27, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.wheelSlipFL</code>.
     */
    public Double getWheelslipfl() {
        return (Double) get(27);
    }

    /**
     * Setter for <code>F1GameDB.MotionData.wheelSlipFR</code>.
     */
    public void setWheelslipfr(Double value) {
        set(28, value);
    }

    /**
     * Getter for <code>F1GameDB.MotionData.wheelSlipFR</code>.
     */
    public Double getWheelslipfr() {
        return (Double) get(28);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MotiondataRecord
     */
    public MotiondataRecord() {
        super(Motiondata.MOTIONDATA);
    }

    /**
     * Create a detached, initialised MotiondataRecord
     */
    public MotiondataRecord(Integer idmotiondata, Long sessionid, Double sessiontime, Double worldvelocityx, Double worldvelocityy, Double worldvelocityz, Double gforcelateral, Double gforcelongitudinal, Double gforcevertical, Double yaw, Double pitch, Double roll, Double suspensionpositionrr, Double suspensionpositionrl, Double suspensionpositionfl, Double suspensionpositionfr, Double suspensionaccelerationrr, Double suspensionvelocityrr, Double suspensionvelocityrl, Double suspensionvelocityfl, Double suspensionvelocityfr, Double frontwheelsangle, Double suspensionaccelerationrl, Double suspensionaccelerationfl, Double suspensionaccelerationfr, Double wheelsliprr, Double wheelsliprl, Double wheelslipfl, Double wheelslipfr) {
        super(Motiondata.MOTIONDATA);

        set(0, idmotiondata);
        set(1, sessionid);
        set(2, sessiontime);
        set(3, worldvelocityx);
        set(4, worldvelocityy);
        set(5, worldvelocityz);
        set(6, gforcelateral);
        set(7, gforcelongitudinal);
        set(8, gforcevertical);
        set(9, yaw);
        set(10, pitch);
        set(11, roll);
        set(12, suspensionpositionrr);
        set(13, suspensionpositionrl);
        set(14, suspensionpositionfl);
        set(15, suspensionpositionfr);
        set(16, suspensionaccelerationrr);
        set(17, suspensionvelocityrr);
        set(18, suspensionvelocityrl);
        set(19, suspensionvelocityfl);
        set(20, suspensionvelocityfr);
        set(21, frontwheelsangle);
        set(22, suspensionaccelerationrl);
        set(23, suspensionaccelerationfl);
        set(24, suspensionaccelerationfr);
        set(25, wheelsliprr);
        set(26, wheelsliprl);
        set(27, wheelslipfl);
        set(28, wheelslipfr);
    }
}
