/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Nationalities;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Information of natinalities specified by F1 2018.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NationalitiesRecord extends UpdatableRecordImpl<NationalitiesRecord> implements Record2<Short, String> {

    private static final long serialVersionUID = 1722734756;

    /**
     * Setter for <code>F1GameDB.Nationalities.idNationality</code>.
     */
    public void setIdnationality(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.Nationalities.idNationality</code>.
     */
    public Short getIdnationality() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>F1GameDB.Nationalities.nationalityName</code>.
     */
    public void setNationalityname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.Nationalities.nationalityName</code>.
     */
    public String getNationalityname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Short, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Short, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return Nationalities.NATIONALITIES.IDNATIONALITY;
    }

    @Override
    public Field<String> field2() {
        return Nationalities.NATIONALITIES.NATIONALITYNAME;
    }

    @Override
    public Short component1() {
        return getIdnationality();
    }

    @Override
    public String component2() {
        return getNationalityname();
    }

    @Override
    public Short value1() {
        return getIdnationality();
    }

    @Override
    public String value2() {
        return getNationalityname();
    }

    @Override
    public NationalitiesRecord value1(Short value) {
        setIdnationality(value);
        return this;
    }

    @Override
    public NationalitiesRecord value2(String value) {
        setNationalityname(value);
        return this;
    }

    @Override
    public NationalitiesRecord values(Short value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NationalitiesRecord
     */
    public NationalitiesRecord() {
        super(Nationalities.NATIONALITIES);
    }

    /**
     * Create a detached, initialised NationalitiesRecord
     */
    public NationalitiesRecord(Short idnationality, String nationalityname) {
        super(Nationalities.NATIONALITIES);

        set(0, idnationality);
        set(1, nationalityname);
    }
}
