/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Sessionendstatus;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Car status at the end of the session: damages fuel remainings etc. 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionendstatusRecord extends UpdatableRecordImpl<SessionendstatusRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1460660021;

    /**
     * Setter for <code>F1GameDB.SessionEndStatus.sessionId</code>.
     */
    public void setSessionid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.SessionEndStatus.sessionId</code>.
     */
    public Integer getSessionid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>F1GameDB.SessionEndStatus.fuelRemain</code>.
     */
    public void setFuelremain(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.SessionEndStatus.fuelRemain</code>.
     */
    public String getFuelremain() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sessionendstatus.SESSIONENDSTATUS.SESSIONID;
    }

    @Override
    public Field<String> field2() {
        return Sessionendstatus.SESSIONENDSTATUS.FUELREMAIN;
    }

    @Override
    public Integer component1() {
        return getSessionid();
    }

    @Override
    public String component2() {
        return getFuelremain();
    }

    @Override
    public Integer value1() {
        return getSessionid();
    }

    @Override
    public String value2() {
        return getFuelremain();
    }

    @Override
    public SessionendstatusRecord value1(Integer value) {
        setSessionid(value);
        return this;
    }

    @Override
    public SessionendstatusRecord value2(String value) {
        setFuelremain(value);
        return this;
    }

    @Override
    public SessionendstatusRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionendstatusRecord
     */
    public SessionendstatusRecord() {
        super(Sessionendstatus.SESSIONENDSTATUS);
    }

    /**
     * Create a detached, initialised SessionendstatusRecord
     */
    public SessionendstatusRecord(Integer sessionid, String fuelremain) {
        super(Sessionendstatus.SESSIONENDSTATUS);

        set(0, sessionid);
        set(1, fuelremain);
    }
}
