/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Teams;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Store information of all teams specified by F1 2018.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamsRecord extends UpdatableRecordImpl<TeamsRecord> implements Record2<Short, String> {

    private static final long serialVersionUID = -92671757;

    /**
     * Setter for <code>F1GameDB.Teams.idTeam</code>.
     */
    public void setIdteam(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.Teams.idTeam</code>.
     */
    public Short getIdteam() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>F1GameDB.Teams.teamName</code>.
     */
    public void setTeamname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.Teams.teamName</code>.
     */
    public String getTeamname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Short, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Short, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return Teams.TEAMS.IDTEAM;
    }

    @Override
    public Field<String> field2() {
        return Teams.TEAMS.TEAMNAME;
    }

    @Override
    public Short component1() {
        return getIdteam();
    }

    @Override
    public String component2() {
        return getTeamname();
    }

    @Override
    public Short value1() {
        return getIdteam();
    }

    @Override
    public String value2() {
        return getTeamname();
    }

    @Override
    public TeamsRecord value1(Short value) {
        setIdteam(value);
        return this;
    }

    @Override
    public TeamsRecord value2(String value) {
        setTeamname(value);
        return this;
    }

    @Override
    public TeamsRecord values(Short value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsRecord
     */
    public TeamsRecord() {
        super(Teams.TEAMS);
    }

    /**
     * Create a detached, initialised TeamsRecord
     */
    public TeamsRecord(Short idteam, String teamname) {
        super(Teams.TEAMS);

        set(0, idteam);
        set(1, teamname);
    }
}
