/*
 * This file is generated by jOOQ.
 */
package dbconn.tables.records;


import dbconn.tables.Tracks;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Tracks information specified by F1 2018.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TracksRecord extends UpdatableRecordImpl<TracksRecord> implements Record2<Short, String> {

    private static final long serialVersionUID = 622775852;

    /**
     * Setter for <code>F1GameDB.Tracks.idTrack</code>.
     */
    public void setIdtrack(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>F1GameDB.Tracks.idTrack</code>.
     */
    public Short getIdtrack() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>F1GameDB.Tracks.trackName</code>.
     */
    public void setTrackname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>F1GameDB.Tracks.trackName</code>.
     */
    public String getTrackname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Short, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Short, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return Tracks.TRACKS.IDTRACK;
    }

    @Override
    public Field<String> field2() {
        return Tracks.TRACKS.TRACKNAME;
    }

    @Override
    public Short component1() {
        return getIdtrack();
    }

    @Override
    public String component2() {
        return getTrackname();
    }

    @Override
    public Short value1() {
        return getIdtrack();
    }

    @Override
    public String value2() {
        return getTrackname();
    }

    @Override
    public TracksRecord value1(Short value) {
        setIdtrack(value);
        return this;
    }

    @Override
    public TracksRecord value2(String value) {
        setTrackname(value);
        return this;
    }

    @Override
    public TracksRecord values(Short value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TracksRecord
     */
    public TracksRecord() {
        super(Tracks.TRACKS);
    }

    /**
     * Create a detached, initialised TracksRecord
     */
    public TracksRecord(Short idtrack, String trackname) {
        super(Tracks.TRACKS);

        set(0, idtrack);
        set(1, trackname);
    }
}
