/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables.records;


import ndbconn.tables.Floatdata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A table to store data from UDP packets that have float type.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FloatdataRecord extends UpdatableRecordImpl<FloatdataRecord> implements Record5<Integer, Short, Double, Integer, Integer> {

    private static final long serialVersionUID = 1267325806;

    /**
     * Setter for <code>NewF1DB.FloatData.idData</code>.
     */
    public void setIddata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.idData</code>.
     */
    public Integer getIddata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.dataName</code>.
     */
    public void setDataname(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.dataName</code>.
     */
    public Short getDataname() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.data</code>.
     */
    public void setData(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.data</code>.
     */
    public Double getData() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.packetId</code>.
     */
    public void setPacketid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.packetId</code>.
     */
    public Integer getPacketid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.sessionId</code>.
     */
    public void setSessionid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.sessionId</code>.
     */
    public Integer getSessionid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Short, Double, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Short, Double, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Floatdata.FLOATDATA.IDDATA;
    }

    @Override
    public Field<Short> field2() {
        return Floatdata.FLOATDATA.DATANAME;
    }

    @Override
    public Field<Double> field3() {
        return Floatdata.FLOATDATA.DATA;
    }

    @Override
    public Field<Integer> field4() {
        return Floatdata.FLOATDATA.PACKETID;
    }

    @Override
    public Field<Integer> field5() {
        return Floatdata.FLOATDATA.SESSIONID;
    }

    @Override
    public Integer component1() {
        return getIddata();
    }

    @Override
    public Short component2() {
        return getDataname();
    }

    @Override
    public Double component3() {
        return getData();
    }

    @Override
    public Integer component4() {
        return getPacketid();
    }

    @Override
    public Integer component5() {
        return getSessionid();
    }

    @Override
    public Integer value1() {
        return getIddata();
    }

    @Override
    public Short value2() {
        return getDataname();
    }

    @Override
    public Double value3() {
        return getData();
    }

    @Override
    public Integer value4() {
        return getPacketid();
    }

    @Override
    public Integer value5() {
        return getSessionid();
    }

    @Override
    public FloatdataRecord value1(Integer value) {
        setIddata(value);
        return this;
    }

    @Override
    public FloatdataRecord value2(Short value) {
        setDataname(value);
        return this;
    }

    @Override
    public FloatdataRecord value3(Double value) {
        setData(value);
        return this;
    }

    @Override
    public FloatdataRecord value4(Integer value) {
        setPacketid(value);
        return this;
    }

    @Override
    public FloatdataRecord value5(Integer value) {
        setSessionid(value);
        return this;
    }

    @Override
    public FloatdataRecord values(Integer value1, Short value2, Double value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FloatdataRecord
     */
    public FloatdataRecord() {
        super(Floatdata.FLOATDATA);
    }

    /**
     * Create a detached, initialised FloatdataRecord
     */
    public FloatdataRecord(Integer iddata, Short dataname, Double data, Integer packetid, Integer sessionid) {
        super(Floatdata.FLOATDATA);

        set(0, iddata);
        set(1, dataname);
        set(2, data);
        set(3, packetid);
        set(4, sessionid);
    }
}
