/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables.records;


import java.time.LocalDateTime;

import ndbconn.tables.Floatdata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A table to store data from UDP packets that have float type.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FloatdataRecord extends UpdatableRecordImpl<FloatdataRecord> implements Record6<Integer, Short, Long, Double, LocalDateTime, Double> {

    private static final long serialVersionUID = 1064507082;

    /**
     * Setter for <code>NewF1DB.FloatData.idData</code>.
     */
    public void setIddata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.idData</code>.
     */
    public Integer getIddata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.dataName</code>.
     */
    public void setDataname(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.dataName</code>.
     */
    public Short getDataname() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.sessionUID</code>.
     */
    public void setSessionuid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.sessionUID</code>.
     */
    public Long getSessionuid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.sessionTime</code>.
     */
    public void setSessiontime(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.sessionTime</code>.
     */
    public Double getSessiontime() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.arriveTime</code>.
     */
    public void setArrivetime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.arriveTime</code>.
     */
    public LocalDateTime getArrivetime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>NewF1DB.FloatData.data</code>.
     */
    public void setData(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>NewF1DB.FloatData.data</code>.
     */
    public Double getData() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Short, Long, Double, LocalDateTime, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Short, Long, Double, LocalDateTime, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Floatdata.FLOATDATA.IDDATA;
    }

    @Override
    public Field<Short> field2() {
        return Floatdata.FLOATDATA.DATANAME;
    }

    @Override
    public Field<Long> field3() {
        return Floatdata.FLOATDATA.SESSIONUID;
    }

    @Override
    public Field<Double> field4() {
        return Floatdata.FLOATDATA.SESSIONTIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Floatdata.FLOATDATA.ARRIVETIME;
    }

    @Override
    public Field<Double> field6() {
        return Floatdata.FLOATDATA.DATA;
    }

    @Override
    public Integer component1() {
        return getIddata();
    }

    @Override
    public Short component2() {
        return getDataname();
    }

    @Override
    public Long component3() {
        return getSessionuid();
    }

    @Override
    public Double component4() {
        return getSessiontime();
    }

    @Override
    public LocalDateTime component5() {
        return getArrivetime();
    }

    @Override
    public Double component6() {
        return getData();
    }

    @Override
    public Integer value1() {
        return getIddata();
    }

    @Override
    public Short value2() {
        return getDataname();
    }

    @Override
    public Long value3() {
        return getSessionuid();
    }

    @Override
    public Double value4() {
        return getSessiontime();
    }

    @Override
    public LocalDateTime value5() {
        return getArrivetime();
    }

    @Override
    public Double value6() {
        return getData();
    }

    @Override
    public FloatdataRecord value1(Integer value) {
        setIddata(value);
        return this;
    }

    @Override
    public FloatdataRecord value2(Short value) {
        setDataname(value);
        return this;
    }

    @Override
    public FloatdataRecord value3(Long value) {
        setSessionuid(value);
        return this;
    }

    @Override
    public FloatdataRecord value4(Double value) {
        setSessiontime(value);
        return this;
    }

    @Override
    public FloatdataRecord value5(LocalDateTime value) {
        setArrivetime(value);
        return this;
    }

    @Override
    public FloatdataRecord value6(Double value) {
        setData(value);
        return this;
    }

    @Override
    public FloatdataRecord values(Integer value1, Short value2, Long value3, Double value4, LocalDateTime value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FloatdataRecord
     */
    public FloatdataRecord() {
        super(Floatdata.FLOATDATA);
    }

    /**
     * Create a detached, initialised FloatdataRecord
     */
    public FloatdataRecord(Integer iddata, Short dataname, Long sessionuid, Double sessiontime, LocalDateTime arrivetime, Double data) {
        super(Floatdata.FLOATDATA);

        set(0, iddata);
        set(1, dataname);
        set(2, sessionuid);
        set(3, sessiontime);
        set(4, arrivetime);
        set(5, data);
    }
}
