/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables.records;


import java.time.LocalDateTime;

import ndbconn.tables.Int16data;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Int16dataRecord extends UpdatableRecordImpl<Int16dataRecord> implements Record6<Integer, Short, Short, Long, Double, LocalDateTime> {

    private static final long serialVersionUID = -1991213015;

    /**
     * Setter for <code>NewF1DB.Int16Data.idData</code>.
     */
    public void setIddata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>NewF1DB.Int16Data.idData</code>.
     */
    public Integer getIddata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>NewF1DB.Int16Data.dataName</code>.
     */
    public void setDataname(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>NewF1DB.Int16Data.dataName</code>.
     */
    public Short getDataname() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>NewF1DB.Int16Data.data</code>.
     */
    public void setData(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>NewF1DB.Int16Data.data</code>.
     */
    public Short getData() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>NewF1DB.Int16Data.sessionUID</code>.
     */
    public void setSessionuid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>NewF1DB.Int16Data.sessionUID</code>.
     */
    public Long getSessionuid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>NewF1DB.Int16Data.sessionTime</code>.
     */
    public void setSessiontime(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>NewF1DB.Int16Data.sessionTime</code>.
     */
    public Double getSessiontime() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>NewF1DB.Int16Data.arriveTime</code>.
     */
    public void setArrivetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>NewF1DB.Int16Data.arriveTime</code>.
     */
    public LocalDateTime getArrivetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Short, Short, Long, Double, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Short, Short, Long, Double, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Int16data.INT16DATA.IDDATA;
    }

    @Override
    public Field<Short> field2() {
        return Int16data.INT16DATA.DATANAME;
    }

    @Override
    public Field<Short> field3() {
        return Int16data.INT16DATA.DATA;
    }

    @Override
    public Field<Long> field4() {
        return Int16data.INT16DATA.SESSIONUID;
    }

    @Override
    public Field<Double> field5() {
        return Int16data.INT16DATA.SESSIONTIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Int16data.INT16DATA.ARRIVETIME;
    }

    @Override
    public Integer component1() {
        return getIddata();
    }

    @Override
    public Short component2() {
        return getDataname();
    }

    @Override
    public Short component3() {
        return getData();
    }

    @Override
    public Long component4() {
        return getSessionuid();
    }

    @Override
    public Double component5() {
        return getSessiontime();
    }

    @Override
    public LocalDateTime component6() {
        return getArrivetime();
    }

    @Override
    public Integer value1() {
        return getIddata();
    }

    @Override
    public Short value2() {
        return getDataname();
    }

    @Override
    public Short value3() {
        return getData();
    }

    @Override
    public Long value4() {
        return getSessionuid();
    }

    @Override
    public Double value5() {
        return getSessiontime();
    }

    @Override
    public LocalDateTime value6() {
        return getArrivetime();
    }

    @Override
    public Int16dataRecord value1(Integer value) {
        setIddata(value);
        return this;
    }

    @Override
    public Int16dataRecord value2(Short value) {
        setDataname(value);
        return this;
    }

    @Override
    public Int16dataRecord value3(Short value) {
        setData(value);
        return this;
    }

    @Override
    public Int16dataRecord value4(Long value) {
        setSessionuid(value);
        return this;
    }

    @Override
    public Int16dataRecord value5(Double value) {
        setSessiontime(value);
        return this;
    }

    @Override
    public Int16dataRecord value6(LocalDateTime value) {
        setArrivetime(value);
        return this;
    }

    @Override
    public Int16dataRecord values(Integer value1, Short value2, Short value3, Long value4, Double value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Int16dataRecord
     */
    public Int16dataRecord() {
        super(Int16data.INT16DATA);
    }

    /**
     * Create a detached, initialised Int16dataRecord
     */
    public Int16dataRecord(Integer iddata, Short dataname, Short data, Long sessionuid, Double sessiontime, LocalDateTime arrivetime) {
        super(Int16data.INT16DATA);

        set(0, iddata);
        set(1, dataname);
        set(2, data);
        set(3, sessionuid);
        set(4, sessiontime);
        set(5, arrivetime);
    }
}
