/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables.records;


import java.time.LocalDateTime;

import ndbconn.tables.Int32data;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A table to store data from UDP packets that have int32 type.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Int32dataRecord extends UpdatableRecordImpl<Int32dataRecord> implements Record6<Integer, Short, Long, Double, LocalDateTime, Integer> {

    private static final long serialVersionUID = -2084412532;

    /**
     * Setter for <code>NewF1DB.Int32Data.idData</code>.
     */
    public void setIddata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>NewF1DB.Int32Data.idData</code>.
     */
    public Integer getIddata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>NewF1DB.Int32Data.dataName</code>.
     */
    public void setDataname(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>NewF1DB.Int32Data.dataName</code>.
     */
    public Short getDataname() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>NewF1DB.Int32Data.senssionUID</code>.
     */
    public void setSenssionuid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>NewF1DB.Int32Data.senssionUID</code>.
     */
    public Long getSenssionuid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>NewF1DB.Int32Data.sessionTime</code>.
     */
    public void setSessiontime(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>NewF1DB.Int32Data.sessionTime</code>.
     */
    public Double getSessiontime() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>NewF1DB.Int32Data.arriveTime</code>.
     */
    public void setArrivetime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>NewF1DB.Int32Data.arriveTime</code>.
     */
    public LocalDateTime getArrivetime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>NewF1DB.Int32Data.data</code>.
     */
    public void setData(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>NewF1DB.Int32Data.data</code>.
     */
    public Integer getData() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Short, Long, Double, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Short, Long, Double, LocalDateTime, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Int32data.INT32DATA.IDDATA;
    }

    @Override
    public Field<Short> field2() {
        return Int32data.INT32DATA.DATANAME;
    }

    @Override
    public Field<Long> field3() {
        return Int32data.INT32DATA.SENSSIONUID;
    }

    @Override
    public Field<Double> field4() {
        return Int32data.INT32DATA.SESSIONTIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Int32data.INT32DATA.ARRIVETIME;
    }

    @Override
    public Field<Integer> field6() {
        return Int32data.INT32DATA.DATA;
    }

    @Override
    public Integer component1() {
        return getIddata();
    }

    @Override
    public Short component2() {
        return getDataname();
    }

    @Override
    public Long component3() {
        return getSenssionuid();
    }

    @Override
    public Double component4() {
        return getSessiontime();
    }

    @Override
    public LocalDateTime component5() {
        return getArrivetime();
    }

    @Override
    public Integer component6() {
        return getData();
    }

    @Override
    public Integer value1() {
        return getIddata();
    }

    @Override
    public Short value2() {
        return getDataname();
    }

    @Override
    public Long value3() {
        return getSenssionuid();
    }

    @Override
    public Double value4() {
        return getSessiontime();
    }

    @Override
    public LocalDateTime value5() {
        return getArrivetime();
    }

    @Override
    public Integer value6() {
        return getData();
    }

    @Override
    public Int32dataRecord value1(Integer value) {
        setIddata(value);
        return this;
    }

    @Override
    public Int32dataRecord value2(Short value) {
        setDataname(value);
        return this;
    }

    @Override
    public Int32dataRecord value3(Long value) {
        setSenssionuid(value);
        return this;
    }

    @Override
    public Int32dataRecord value4(Double value) {
        setSessiontime(value);
        return this;
    }

    @Override
    public Int32dataRecord value5(LocalDateTime value) {
        setArrivetime(value);
        return this;
    }

    @Override
    public Int32dataRecord value6(Integer value) {
        setData(value);
        return this;
    }

    @Override
    public Int32dataRecord values(Integer value1, Short value2, Long value3, Double value4, LocalDateTime value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Int32dataRecord
     */
    public Int32dataRecord() {
        super(Int32data.INT32DATA);
    }

    /**
     * Create a detached, initialised Int32dataRecord
     */
    public Int32dataRecord(Integer iddata, Short dataname, Long senssionuid, Double sessiontime, LocalDateTime arrivetime, Integer data) {
        super(Int32data.INT32DATA);

        set(0, iddata);
        set(1, dataname);
        set(2, senssionuid);
        set(3, sessiontime);
        set(4, arrivetime);
        set(5, data);
    }
}
