/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables.records;


import ndbconn.tables.Strdata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StrdataRecord extends UpdatableRecordImpl<StrdataRecord> implements Record5<Integer, String, Short, Integer, Integer> {

    private static final long serialVersionUID = -1650256126;

    /**
     * Setter for <code>NewF1DB.StrData.idData</code>.
     */
    public void setIddata(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>NewF1DB.StrData.idData</code>.
     */
    public Integer getIddata() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>NewF1DB.StrData.data</code>.
     */
    public void setData(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>NewF1DB.StrData.data</code>.
     */
    public String getData() {
        return (String) get(1);
    }

    /**
     * Setter for <code>NewF1DB.StrData.dataName</code>.
     */
    public void setDataname(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>NewF1DB.StrData.dataName</code>.
     */
    public Short getDataname() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>NewF1DB.StrData.packetId</code>.
     */
    public void setPacketid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>NewF1DB.StrData.packetId</code>.
     */
    public Integer getPacketid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>NewF1DB.StrData.sessionId</code>.
     */
    public void setSessionid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>NewF1DB.StrData.sessionId</code>.
     */
    public Integer getSessionid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Short, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Short, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Strdata.STRDATA.IDDATA;
    }

    @Override
    public Field<String> field2() {
        return Strdata.STRDATA.DATA;
    }

    @Override
    public Field<Short> field3() {
        return Strdata.STRDATA.DATANAME;
    }

    @Override
    public Field<Integer> field4() {
        return Strdata.STRDATA.PACKETID;
    }

    @Override
    public Field<Integer> field5() {
        return Strdata.STRDATA.SESSIONID;
    }

    @Override
    public Integer component1() {
        return getIddata();
    }

    @Override
    public String component2() {
        return getData();
    }

    @Override
    public Short component3() {
        return getDataname();
    }

    @Override
    public Integer component4() {
        return getPacketid();
    }

    @Override
    public Integer component5() {
        return getSessionid();
    }

    @Override
    public Integer value1() {
        return getIddata();
    }

    @Override
    public String value2() {
        return getData();
    }

    @Override
    public Short value3() {
        return getDataname();
    }

    @Override
    public Integer value4() {
        return getPacketid();
    }

    @Override
    public Integer value5() {
        return getSessionid();
    }

    @Override
    public StrdataRecord value1(Integer value) {
        setIddata(value);
        return this;
    }

    @Override
    public StrdataRecord value2(String value) {
        setData(value);
        return this;
    }

    @Override
    public StrdataRecord value3(Short value) {
        setDataname(value);
        return this;
    }

    @Override
    public StrdataRecord value4(Integer value) {
        setPacketid(value);
        return this;
    }

    @Override
    public StrdataRecord value5(Integer value) {
        setSessionid(value);
        return this;
    }

    @Override
    public StrdataRecord values(Integer value1, String value2, Short value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StrdataRecord
     */
    public StrdataRecord() {
        super(Strdata.STRDATA);
    }

    /**
     * Create a detached, initialised StrdataRecord
     */
    public StrdataRecord(Integer iddata, String data, Short dataname, Integer packetid, Integer sessionid) {
        super(Strdata.STRDATA);

        set(0, iddata);
        set(1, data);
        set(2, dataname);
        set(3, packetid);
        set(4, sessionid);
    }
}
