/*
 * This file is generated by jOOQ.
 */
package ndbconn.routines;


import java.time.LocalDateTime;

import ndbconn.Newf1db;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Savefloat extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1425214526;

    /**
     * The parameter <code>NewF1DB.saveFloat.dataIN</code>.
     */
    public static final Parameter<Double> DATAIN = Internal.createParameter("dataIN", org.jooq.impl.SQLDataType.FLOAT, false, false);

    /**
     * The parameter <code>NewF1DB.saveFloat.dname</code>.
     */
    public static final Parameter<String> DNAME = Internal.createParameter("dname", org.jooq.impl.SQLDataType.VARCHAR(45), false, false);

    /**
     * The parameter <code>NewF1DB.saveFloat.sessionUID</code>.
     */
    public static final Parameter<Long> SESSIONUID = Internal.createParameter("sessionUID", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>NewF1DB.saveFloat.sessionTime</code>.
     */
    public static final Parameter<Double> SESSIONTIME = Internal.createParameter("sessionTime", org.jooq.impl.SQLDataType.FLOAT, false, false);

    /**
     * The parameter <code>NewF1DB.saveFloat.arriveTime</code>.
     */
    public static final Parameter<LocalDateTime> ARRIVETIME = Internal.createParameter("arriveTime", org.jooq.impl.SQLDataType.LOCALDATETIME, false, false);

    /**
     * Create a new routine call instance
     */
    public Savefloat() {
        super("saveFloat", Newf1db.NEWF1DB);

        addInParameter(DATAIN);
        addInParameter(DNAME);
        addInParameter(SESSIONUID);
        addInParameter(SESSIONTIME);
        addInParameter(ARRIVETIME);
    }

    /**
     * Set the <code>dataIN</code> parameter IN value to the routine
     */
    public void setDatain(Double value) {
        setValue(DATAIN, value);
    }

    /**
     * Set the <code>dname</code> parameter IN value to the routine
     */
    public void setDname(String value) {
        setValue(DNAME, value);
    }

    /**
     * Set the <code>sessionUID</code> parameter IN value to the routine
     */
    public void setSessionuid(Long value) {
        setValue(SESSIONUID, value);
    }

    /**
     * Set the <code>sessionTime</code> parameter IN value to the routine
     */
    public void setSessiontime(Double value) {
        setValue(SESSIONTIME, value);
    }

    /**
     * Set the <code>arriveTime</code> parameter IN value to the routine
     */
    public void setArrivetime(LocalDateTime value) {
        setValue(ARRIVETIME, value);
    }
}
