/*
 * This file is generated by jOOQ.
 */
package ndbconn.routines;


import java.time.LocalDateTime;

import ndbconn.Newf1db;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saveint8data extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 22261595;

    /**
     * The parameter <code>NewF1DB.saveInt8Data.dataIn</code>.
     */
    public static final Parameter<Byte> DATAIN = Internal.createParameter("dataIn", org.jooq.impl.SQLDataType.TINYINT, false, false);

    /**
     * The parameter <code>NewF1DB.saveInt8Data.dname</code>.
     */
    public static final Parameter<String> DNAME = Internal.createParameter("dname", org.jooq.impl.SQLDataType.VARCHAR(45), false, false);

    /**
     * The parameter <code>NewF1DB.saveInt8Data.sessionUID</code>.
     */
    public static final Parameter<Long> SESSIONUID = Internal.createParameter("sessionUID", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>NewF1DB.saveInt8Data.sessionTime</code>.
     */
    public static final Parameter<Double> SESSIONTIME = Internal.createParameter("sessionTime", org.jooq.impl.SQLDataType.FLOAT, false, false);

    /**
     * The parameter <code>NewF1DB.saveInt8Data.arriveTime</code>.
     */
    public static final Parameter<LocalDateTime> ARRIVETIME = Internal.createParameter("arriveTime", org.jooq.impl.SQLDataType.LOCALDATETIME, false, false);

    /**
     * Create a new routine call instance
     */
    public Saveint8data() {
        super("saveInt8Data", Newf1db.NEWF1DB);

        addInParameter(DATAIN);
        addInParameter(DNAME);
        addInParameter(SESSIONUID);
        addInParameter(SESSIONTIME);
        addInParameter(ARRIVETIME);
    }

    /**
     * Set the <code>dataIn</code> parameter IN value to the routine
     */
    public void setDatain(Byte value) {
        setValue(DATAIN, value);
    }

    /**
     * Set the <code>dname</code> parameter IN value to the routine
     */
    public void setDname(String value) {
        setValue(DNAME, value);
    }

    /**
     * Set the <code>sessionUID</code> parameter IN value to the routine
     */
    public void setSessionuid(Long value) {
        setValue(SESSIONUID, value);
    }

    /**
     * Set the <code>sessionTime</code> parameter IN value to the routine
     */
    public void setSessiontime(Double value) {
        setValue(SESSIONTIME, value);
    }

    /**
     * Set the <code>arriveTime</code> parameter IN value to the routine
     */
    public void setArrivetime(LocalDateTime value) {
        setValue(ARRIVETIME, value);
    }
}
