/*
 * This file is generated by jOOQ.
 */
package ndbconn.routines;


import ndbconn.Newf1db;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saveint8 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -169294602;

    /**
     * The parameter <code>NewF1DB.saveInt8.dataIN</code>.
     */
    public static final Parameter<Byte> DATAIN = Internal.createParameter("dataIN", org.jooq.impl.SQLDataType.TINYINT, false, false);

    /**
     * Create a new routine call instance
     */
    public Saveint8() {
        super("saveInt8", Newf1db.NEWF1DB);

        addInParameter(DATAIN);
    }

    /**
     * Set the <code>dataIN</code> parameter IN value to the routine
     */
    public void setDatain(Byte value) {
        setValue(DATAIN, value);
    }
}
