/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables;


import java.util.Arrays;
import java.util.List;

import ndbconn.Indexes;
import ndbconn.Keys;
import ndbconn.Newf1db;
import ndbconn.tables.records.FloatdataRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * A table to store data from UDP packets that have float type.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Floatdata extends TableImpl<FloatdataRecord> {

    private static final long serialVersionUID = 1863528488;

    /**
     * The reference instance of <code>NewF1DB.FloatData</code>
     */
    public static final Floatdata FLOATDATA = new Floatdata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FloatdataRecord> getRecordType() {
        return FloatdataRecord.class;
    }

    /**
     * The column <code>NewF1DB.FloatData.idData</code>.
     */
    public final TableField<FloatdataRecord, Integer> IDDATA = createField(DSL.name("idData"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>NewF1DB.FloatData.dataName</code>.
     */
    public final TableField<FloatdataRecord, Short> DATANAME = createField(DSL.name("dataName"), org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>NewF1DB.FloatData.data</code>.
     */
    public final TableField<FloatdataRecord, Double> DATA = createField(DSL.name("data"), org.jooq.impl.SQLDataType.FLOAT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>NewF1DB.FloatData.packetId</code>.
     */
    public final TableField<FloatdataRecord, Integer> PACKETID = createField(DSL.name("packetId"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>NewF1DB.FloatData.sessionId</code>.
     */
    public final TableField<FloatdataRecord, Integer> SESSIONID = createField(DSL.name("sessionId"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>NewF1DB.FloatData</code> table reference
     */
    public Floatdata() {
        this(DSL.name("FloatData"), null);
    }

    /**
     * Create an aliased <code>NewF1DB.FloatData</code> table reference
     */
    public Floatdata(String alias) {
        this(DSL.name(alias), FLOATDATA);
    }

    /**
     * Create an aliased <code>NewF1DB.FloatData</code> table reference
     */
    public Floatdata(Name alias) {
        this(alias, FLOATDATA);
    }

    private Floatdata(Name alias, Table<FloatdataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Floatdata(Name alias, Table<FloatdataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("A table to store data from UDP packets that have float type."), TableOptions.table());
    }

    public <O extends Record> Floatdata(Table<O> child, ForeignKey<O, FloatdataRecord> key) {
        super(child, key, FLOATDATA);
    }

    @Override
    public Schema getSchema() {
        return Newf1db.NEWF1DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FLOATDATA_FLOATTONAME_IDX, Indexes.FLOATDATA_FLOATTOPACKET_IDX, Indexes.FLOATDATA_FLOATTOSESSION_IDX);
    }

    @Override
    public Identity<FloatdataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FLOATDATA;
    }

    @Override
    public UniqueKey<FloatdataRecord> getPrimaryKey() {
        return Keys.KEY_FLOATDATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<FloatdataRecord>> getKeys() {
        return Arrays.<UniqueKey<FloatdataRecord>>asList(Keys.KEY_FLOATDATA_PRIMARY);
    }

    @Override
    public List<ForeignKey<FloatdataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FloatdataRecord, ?>>asList(Keys.FLOATTONAME, Keys.FLOATTOPACKET, Keys.FLOATTOSESSION);
    }

    public Datanames datanames() {
        return new Datanames(this, Keys.FLOATTONAME);
    }

    public Packets packets() {
        return new Packets(this, Keys.FLOATTOPACKET);
    }

    public Sessions sessions() {
        return new Sessions(this, Keys.FLOATTOSESSION);
    }

    @Override
    public Floatdata as(String alias) {
        return new Floatdata(DSL.name(alias), this);
    }

    @Override
    public Floatdata as(Name alias) {
        return new Floatdata(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Floatdata rename(String name) {
        return new Floatdata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Floatdata rename(Name name) {
        return new Floatdata(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Short, Double, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
