/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import ndbconn.Indexes;
import ndbconn.Keys;
import ndbconn.Newf1db;
import ndbconn.tables.records.Int8dataRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Int8data extends TableImpl<Int8dataRecord> {

    private static final long serialVersionUID = 832520977;

    /**
     * The reference instance of <code>NewF1DB.Int8Data</code>
     */
    public static final Int8data INT8DATA = new Int8data();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Int8dataRecord> getRecordType() {
        return Int8dataRecord.class;
    }

    /**
     * The column <code>NewF1DB.Int8Data.idData</code>.
     */
    public final TableField<Int8dataRecord, Integer> IDDATA = createField(DSL.name("idData"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>NewF1DB.Int8Data.data</code>.
     */
    public final TableField<Int8dataRecord, Byte> DATA = createField(DSL.name("data"), org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>NewF1DB.Int8Data.sessionUID</code>.
     */
    public final TableField<Int8dataRecord, Long> SESSIONUID = createField(DSL.name("sessionUID"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>NewF1DB.Int8Data.sessionTime</code>.
     */
    public final TableField<Int8dataRecord, Double> SESSIONTIME = createField(DSL.name("sessionTime"), org.jooq.impl.SQLDataType.FLOAT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * The column <code>NewF1DB.Int8Data.arriveTime</code>.
     */
    public final TableField<Int8dataRecord, LocalDateTime> ARRIVETIME = createField(DSL.name("arriveTime"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>NewF1DB.Int8Data.dataName</code>.
     */
    public final TableField<Int8dataRecord, Short> DATANAME = createField(DSL.name("dataName"), org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>NewF1DB.Int8Data</code> table reference
     */
    public Int8data() {
        this(DSL.name("Int8Data"), null);
    }

    /**
     * Create an aliased <code>NewF1DB.Int8Data</code> table reference
     */
    public Int8data(String alias) {
        this(DSL.name(alias), INT8DATA);
    }

    /**
     * Create an aliased <code>NewF1DB.Int8Data</code> table reference
     */
    public Int8data(Name alias) {
        this(alias, INT8DATA);
    }

    private Int8data(Name alias, Table<Int8dataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Int8data(Name alias, Table<Int8dataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Int8data(Table<O> child, ForeignKey<O, Int8dataRecord> key) {
        super(child, key, INT8DATA);
    }

    @Override
    public Schema getSchema() {
        return Newf1db.NEWF1DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INT8DATA_INT8TONAME_IDX);
    }

    @Override
    public UniqueKey<Int8dataRecord> getPrimaryKey() {
        return Keys.KEY_INT8DATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<Int8dataRecord>> getKeys() {
        return Arrays.<UniqueKey<Int8dataRecord>>asList(Keys.KEY_INT8DATA_PRIMARY);
    }

    @Override
    public List<ForeignKey<Int8dataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<Int8dataRecord, ?>>asList(Keys.INT8TONAME);
    }

    public Datanames datanames() {
        return new Datanames(this, Keys.INT8TONAME);
    }

    @Override
    public Int8data as(String alias) {
        return new Int8data(DSL.name(alias), this);
    }

    @Override
    public Int8data as(Name alias) {
        return new Int8data(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Int8data rename(String name) {
        return new Int8data(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Int8data rename(Name name) {
        return new Int8data(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Byte, Long, Double, LocalDateTime, Short> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
