/*
 * This file is generated by jOOQ.
 */
package ndbconn.tables;


import java.util.Arrays;
import java.util.List;

import ndbconn.Indexes;
import ndbconn.Keys;
import ndbconn.Newf1db;
import ndbconn.tables.records.Uint16dataRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uint16data extends TableImpl<Uint16dataRecord> {

    private static final long serialVersionUID = 1769302902;

    /**
     * The reference instance of <code>NewF1DB.UInt16Data</code>
     */
    public static final Uint16data UINT16DATA = new Uint16data();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Uint16dataRecord> getRecordType() {
        return Uint16dataRecord.class;
    }

    /**
     * The column <code>NewF1DB.UInt16Data.idData</code>.
     */
    public final TableField<Uint16dataRecord, Integer> IDDATA = createField(DSL.name("idData"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>NewF1DB.UInt16Data.data</code>.
     */
    public final TableField<Uint16dataRecord, UShort> DATA = createField(DSL.name("data"), org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "");

    /**
     * The column <code>NewF1DB.UInt16Data.dataName</code>.
     */
    public final TableField<Uint16dataRecord, Short> DATANAME = createField(DSL.name("dataName"), org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>NewF1DB.UInt16Data.packetId</code>.
     */
    public final TableField<Uint16dataRecord, Integer> PACKETID = createField(DSL.name("packetId"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>NewF1DB.UInt16Data.sessionId</code>.
     */
    public final TableField<Uint16dataRecord, Integer> SESSIONID = createField(DSL.name("sessionId"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>NewF1DB.UInt16Data</code> table reference
     */
    public Uint16data() {
        this(DSL.name("UInt16Data"), null);
    }

    /**
     * Create an aliased <code>NewF1DB.UInt16Data</code> table reference
     */
    public Uint16data(String alias) {
        this(DSL.name(alias), UINT16DATA);
    }

    /**
     * Create an aliased <code>NewF1DB.UInt16Data</code> table reference
     */
    public Uint16data(Name alias) {
        this(alias, UINT16DATA);
    }

    private Uint16data(Name alias, Table<Uint16dataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Uint16data(Name alias, Table<Uint16dataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Uint16data(Table<O> child, ForeignKey<O, Uint16dataRecord> key) {
        super(child, key, UINT16DATA);
    }

    @Override
    public Schema getSchema() {
        return Newf1db.NEWF1DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UINT16DATA_UINT16TONAME_IDX, Indexes.UINT16DATA_UINT16TOPACKET_IDX, Indexes.UINT16DATA_UINT16TOSESSION_IDX);
    }

    @Override
    public Identity<Uint16dataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_UINT16DATA;
    }

    @Override
    public UniqueKey<Uint16dataRecord> getPrimaryKey() {
        return Keys.KEY_UINT16DATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<Uint16dataRecord>> getKeys() {
        return Arrays.<UniqueKey<Uint16dataRecord>>asList(Keys.KEY_UINT16DATA_PRIMARY);
    }

    @Override
    public List<ForeignKey<Uint16dataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<Uint16dataRecord, ?>>asList(Keys.UINT16TONAME, Keys.UINT16TOPACKET, Keys.UINT16TOSESSION);
    }

    public Datanames datanames() {
        return new Datanames(this, Keys.UINT16TONAME);
    }

    public Packets packets() {
        return new Packets(this, Keys.UINT16TOPACKET);
    }

    public Sessions sessions() {
        return new Sessions(this, Keys.UINT16TOSESSION);
    }

    @Override
    public Uint16data as(String alias) {
        return new Uint16data(DSL.name(alias), this);
    }

    @Override
    public Uint16data as(Name alias) {
        return new Uint16data(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Uint16data rename(String name) {
        return new Uint16data(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Uint16data rename(Name name) {
        return new Uint16data(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, UShort, Short, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
