/*
 * This file is generated by jOOQ.
 */
package ndbconn;


import ndbconn.routines.Saveint8;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in NewF1DB
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>NewF1DB.saveInt8</code>
     */
    public static void saveint8(Configuration configuration, Byte datain) {
        Saveint8 p = new Saveint8();
        p.setDatain(datain);

        p.execute(configuration);
    }
}
