/*
 * This file is generated by jOOQ.
 */
package ndbconn;


import ndbconn.tables.Datanames;
import ndbconn.tables.Floatdata;
import ndbconn.tables.Int16data;
import ndbconn.tables.Int32data;
import ndbconn.tables.Int8data;
import ndbconn.tables.Packets;
import ndbconn.tables.Sessions;
import ndbconn.tables.Strdata;
import ndbconn.tables.Uint16data;
import ndbconn.tables.Uint32data;
import ndbconn.tables.Uint8data;


/**
 * Convenience access to all tables in NewF1DB
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * A table to store different names of the data stored in the data table. 
     */
    public static final Datanames DATANAMES = Datanames.DATANAMES;

    /**
     * A table to store data from UDP packets that have float type.
     */
    public static final Floatdata FLOATDATA = Floatdata.FLOATDATA;

    /**
     * The table <code>NewF1DB.Int16Data</code>.
     */
    public static final Int16data INT16DATA = Int16data.INT16DATA;

    /**
     * A table to store data from UDP packets that have int32 type.
     */
    public static final Int32data INT32DATA = Int32data.INT32DATA;

    /**
     * The table <code>NewF1DB.Int8Data</code>.
     */
    public static final Int8data INT8DATA = Int8data.INT8DATA;

    /**
     * A table to store common packet information, to avoid reductancy in data table. This table provides timestamp information for the user to reconstruct a complete session. 
     */
    public static final Packets PACKETS = Packets.PACKETS;

    /**
     * Store session UID, to avoid duplicate values in table Packets. The user can join this table with the data table to filter data by sessions. 
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>NewF1DB.StrData</code>.
     */
    public static final Strdata STRDATA = Strdata.STRDATA;

    /**
     * The table <code>NewF1DB.UInt16Data</code>.
     */
    public static final Uint16data UINT16DATA = Uint16data.UINT16DATA;

    /**
     * The table <code>NewF1DB.UInt32Data</code>.
     */
    public static final Uint32data UINT32DATA = Uint32data.UINT32DATA;

    /**
     * The table <code>NewF1DB.UInt8Data</code>.
     */
    public static final Uint8data UINT8DATA = Uint8data.UINT8DATA;
}
